### PR TITLE
external value fix

### PR DESCRIPTION
**Pull request by vasilich6107**
Hi @danvick this is a fix for #13 
Could you merge and release

### CODE REVIEW

**Comment by ened** [comment]
Thank you for fixing.. 

Do you want to have a stab at writing a golden test to verify?

**Comment by vasilich6107** [comment]
Hi @ened I'm not sure that I understood your question)

**Comment by danvick** [comment]
I believe @ened is suggesting we have a test to confirm the implementation works

**Comment by vasilich6107** [comment]
Hi @danvick - may be you are right.
For now I have time only for this fix

**Comment by vasilich6107** [comment]
I tested the behaviour by updating the example with button that changes the value from outside

**Comment by danvick** [comment]
LGTM. 

Thanks for contributing @vasilich6107

**Pull request merged**
